#!/usr/bin/env python

from uuid import uuid4
import argparse

def parse():
    parser = argparse.ArgumentParser(
            description="Generate some UUIDs (v4)")
    parser.add_argument("-n", "--number", type=int, help="The number of UUIDs to generate")

    args = parser.parse_args()
    return vars(args)

if __name__ == "__main__":
    args = parse()

    number = 1
    if args["number"] is not None:
        number = max(1, args["number"])

    for i in range(number):
        print(str(uuid4()))
